# SPDX-FileCopyrightText: 2026 NeoRobotNix contributors
# SPDX-License-Identifier: MIT
#
# Assemble a Chromium source tree from info.json (generated by
# pkgs/chromium-update/update.py). Reads every dep record and
# dispatches on its `fetcher` field to produce a fixed-output
# derivation, then stitches the lot into a single `src/` tree.
#
# Pure Nix — no IFD, no network at realise time beyond the FODs.

{
  lib,
  runCommand,
  fetchFromGitiles,
  fetchcipd,
  fetchgcs,
  symlinkJoin,
  infoJson ? ./info.json,
}:

let
  info = builtins.fromJSON (builtins.readFile infoJson);

  fetchDep =
    path: dep:
    if dep.fetcher == "fetchFromGitiles" then
      # fetchFromGitiles uses gitiles' +archive HTTP API (not a git
      # clone), so submodules aren't included by default — and Chromium's
      # DEPS lists each submodule as its own entry anyway.
      fetchFromGitiles { inherit (dep) url rev hash; }
    else if dep.fetcher == "fetchcipd-bundle" then
      if lib.length dep.packages == 1 then
        fetchcipd {
          package = (lib.head dep.packages).package;
          version = (lib.head dep.packages).version;
          sha256 = (lib.head dep.packages).hash;
        }
      else
        symlinkJoin {
          name = "cipd-bundle-${lib.strings.sanitizeDerivationName path}";
          paths = map (
            p:
            fetchcipd {
              inherit (p) package version;
              sha256 = p.hash;
            }
          ) dep.packages;
        }
    else if dep.fetcher == "fetchgcs-bundle" then
      # GCS objects are single files. Wrap them in a directory so
      # copyCommand's `cp -a drv/.` pattern works uniformly. The
      # object_name is preserved relative to the dest dir — this matches
      # the layout Chromium's download_from_google_storage.py hook would
      # produce if we were running hooks.
      runCommand "gcs-bundle-${lib.strings.sanitizeDerivationName path}" { } ''
        mkdir -p $out
        ${lib.concatMapStringsSep "\n" (
          o:
          let
            f = fetchgcs {
              inherit (dep) bucket;
              object = o.object_name;
              hash = o.hash;
            };
          in
          ''
            mkdir -p "$(dirname "$out/${o.object_name}")"
            cp -a ${f} "$out/${o.object_name}"
          ''
        ) dep.objects}
      ''
    else
      throw "src.nix: unknown fetcher ${dep.fetcher} at ${path}";

  fetchedDeps = lib.mapAttrs fetchDep info.deps;

  # Build a list of (path, drv) pairs sorted deepest-last so that the
  # outer `src/` lands first, then subpaths overlay onto it.
  sortedPaths = lib.sort (
    a: b: lib.length (lib.splitString "/" a) < lib.length (lib.splitString "/" b)
  ) (lib.attrNames fetchedDeps);

  copyCommand =
    path:
    let
      drv = fetchedDeps.${path};
    in
    ''
      mkdir -p $out/${path}
      # Preserve mode (crucially the executable bit — the esbuild binary
      # and various tool wrappers rely on it), but drop ownership. Add
      # owner-write after so postPatch can modify sources.
      cp -a --no-preserve=ownership ${drv}/. $out/${path}/
      chmod -R u+w $out/${path} 2>/dev/null || true
    '';
  chromiumRev = info.deps."src".rev;
  skiaRev = info.deps."src/third_party/skia".rev or "unknown";
  dawnRev = info.deps."src/third_party/dawn".rev or "unknown";
in
runCommand "chromium-src-${info.chromium.version}"
  {
    passthru = {
      inherit info fetchedDeps;
      version = info.chromium.version;
    };
  }
  ''
    set -euo pipefail
    mkdir -p $out
    ${lib.concatStringsSep "\n" (map copyCommand sortedPaths)}

    # Files normally produced by Chromium's gclient post-sync hooks
    # (lastchange.py, etc.). Without these `ninja` errors out with
    # "missing and no known rule to make it". Content values mirror
    # what the original robotnix chromium derivation hardcoded.
    mkdir -p $out/src/build/util $out/src/gpu/config $out/src/skia/ext
    echo 'LASTCHANGE=${chromiumRev}-refs/heads/main@{#0}' > $out/src/build/util/LASTCHANGE
    echo '1555555555' > $out/src/build/util/LASTCHANGE.committime
    cat > $out/src/gpu/config/gpu_lists_version.h <<GPU_LISTS
    /* Generated by lastchange.py, do not edit. */
    #ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
    #define GPU_CONFIG_GPU_LISTS_VERSION_H_
    #define GPU_LISTS_VERSION "${chromiumRev}"
    #endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
    GPU_LISTS
    cat > $out/src/skia/ext/skia_commit_hash.h <<SKIA_COMMIT
    /* Generated by lastchange.py, do not edit. */
    #ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
    #define SKIA_EXT_SKIA_COMMIT_HASH_H_
    #define SKIA_COMMIT_HASH "${skiaRev}-"
    #endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
    SKIA_COMMIT

    # Dawn version files: normally written by a gclient hook.
    mkdir -p $out/src/gpu/webgpu
    printf '%s' '${dawnRev}' > $out/src/gpu/webgpu/DAWN_VERSION
    cat > $out/src/gpu/webgpu/dawn_commit_hash.h <<DAWN_COMMIT
    /* Generated by lastchange.py, do not edit. */
    #ifndef GPU_WEBGPU_DAWN_COMMIT_HASH_H_
    #define GPU_WEBGPU_DAWN_COMMIT_HASH_H_
    #define DAWN_COMMIT_HASH "${dawnRev}"
    #endif  // GPU_WEBGPU_DAWN_COMMIT_HASH_H_
    DAWN_COMMIT
  ''
